name: "Test"

on:
  push:
  pull_request:

jobs:

  server:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
            - "6379:6379"

      mongo:
        image: mongo:3.6
        ports:
            - "27017:27017"

      elastic:
        image: elasticsearch:7.17.23
        ports:
            - "9200:9200"
        env:
            discovery.type: single-node

    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: |
        sudo apt-get update
        sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

    - run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - run: pytest tests

  client:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm ci

    - run: npm run build